Repository s1f10220227/sleep-comm-ai, pull requests merged in 2024-09, with the labels that each got.

#34 Create README.md
  README.md
Labels: documentation

#33 Feature/group create join
  src/accounts/views.py
  src/config/settings.py
  src/groups/migrations/0001_initial.py
  src/groups/migrations/0002_remove_group_created_at_remove_group_creator_and_more.py
  src/groups/migrations/0003_alter_groupmember_user.py
  src/groups/models.py
  src/groups/templates/groups/group_menu.html
  src/groups/urls.py
  src/groups/views.py
Labels: bug, enhancement

#49 Feature/add logout functionality and improve home page and login functionality
  src/accounts/templates/accounts/dashboard.html
  src/accounts/templates/accounts/home.html
  src/accounts/urls.py
  src/accounts/views.py
  src/config/settings.py
  src/config/urls.py
  src/groups/views.py
  src/templates/base.html
Labels: enhancement

#55 Feature/Display group members in group menu
  src/groups/templates/groups/group_menu.html
  src/groups/views.py
Labels: enhancement

#64 Feature/add group chat screen
  django/requirements.txt
  docker-compose.yaml
  nginx/default.conf
  src/chat/apps.py
  src/chat/consumers.py
  src/chat/migrations/0002_message.py
  src/chat/models.py
  src/chat/routing.py
  src/chat/static/chat/css/room.css
  src/chat/static/chat/js/room.js
  src/chat/templates/chat/room.html
  src/chat/templatetags/group_tags.py
  src/chat/urls.py
  src/chat/views.py
  src/collected_static/chat/css/room.css
  src/collected_static/chat/js/room.js
  src/config/asgi.py
  src/config/settings.py
  src/groups/models.py
  src/templates/base.html
Labels: enhancement

#66 modify-data-bugs
  src/progress/views.py
Labels: bug

#68 Feature/integrate group menu
  src/accounts/templates/accounts/home.html
  src/accounts/urls.py
  src/accounts/views.py
  src/chat/templates/chat/room.html
  src/config/urls.py
  src/groups/templates/groups/group_management.html
  src/groups/templates/groups/group_menu.html
  src/groups/templates/groups/home.html
  src/groups/templatetags/custom_filters.py
  src/groups/urls.py
  src/groups/views.py
  src/templates/base.html
Labels: enhancement
