Repository s1f10220227/sleep-comm-ai, pull requests merged in 2024-12, with the labels that each got.

#95 Improved chat screen UI
  src/chat/static/chat/js/room.js
  src/chat/templates/chat/room.html
  src/collected_static/admin/css/autocomplete.css
  src/collected_static/admin/css/base.css
  src/collected_static/admin/css/changelists.css
  src/collected_static/admin/css/dark_mode.css
  src/collected_static/admin/css/forms.css
  src/collected_static/admin/css/login.css
  src/collected_static/admin/css/responsive.css
  src/collected_static/admin/css/responsive_rtl.css
  src/collected_static/admin/css/rtl.css
  src/collected_static/admin/css/unusable_password_field.css
  src/collected_static/admin/css/widgets.css
  src/collected_static/admin/img/README.txt
  src/collected_static/admin/img/calendar-icons.svg
  src/collected_static/admin/img/icon-addlink.svg
  src/collected_static/admin/img/icon-changelink.svg
  src/collected_static/admin/js/SelectFilter2.js
  src/collected_static/admin/js/actions.js
  src/collected_static/admin/js/admin/RelatedObjectLookups.js
  src/collected_static/admin/js/popup_response.js
  src/collected_static/admin/js/theme.js
  src/collected_static/admin/js/unusable_password_field.js
  src/collected_static/chat/css/room.css
  src/collected_static/chat/js/room.js
  src/progress/views.py
  src/templates/base.html
Labels: enhancement

#96 Feature/add async process
  .gitignore
  django/requirements.txt
  docker-compose.yaml
  src/chat/consumers.py
  src/chat/static/chat/js/room.js
  src/chat/tasks.py
  src/chat/templates/chat/room.html
  src/collected_static/chat/js/room.js
  src/config/__init__.py
  src/config/celery.py
  src/config/settings.py
Labels: enhancement

#99 Fix/update group limits and cleanup
  .gitignore
  src/groups/models.py
  src/groups/views.py
Labels: bug

#101 Feature/mission multiple generation and voting
  src/chat/migrations/0007_missionoption_vote.py
  src/chat/models.py
  src/chat/templates/chat/room.html
  src/chat/urls.py
  src/chat/views.py
  src/groups/migrations/0004_group_vote_deadline_alter_groupmember_group.py
  src/groups/models.py
Labels: enhancement

#103 Solve everyone's frustrations
  src/accounts/migrations/0002_customuser_age_customuser_gender.py
  src/accounts/models.py
  src/accounts/templates/accounts/login_signup.html
  src/accounts/templates/accounts/privacy_policy.html
  src/accounts/templates/accounts/signup.html
  src/accounts/views.py
Labels: documentation, enhancement

#106 Fix: Fixed an error when voting without selecting a mission option
  src/chat/templates/chat/room.html
  src/chat/views.py
Labels: bug

#111 ai_tips&enter
  src/chat/static/chat/js/room.js
  src/chat/tasks.py
  src/chat/templates/chat/room.html
  src/collected_static/chat/js/room.js
  src/config/celery.py
Labels: enhancement

#122 Ensure consistent formatting of message display tags
  src/chat/templates/chat/room.html
Labels: bug

#124 Feature/update sleep question
  src/chat/migrations/0008_sleepadvice_mission_achievement_and_more.py
  src/chat/migrations/0009_sleepadvice_sleep_duration.py
  src/chat/models.py
  src/chat/static/chat/css/sleep_q.css
  src/chat/static/chat/js/sleep_q.js
  src/chat/tasks.py
  src/chat/templates/chat/feedback_chat.html
  src/chat/templates/chat/pre_group_questions.html
  src/chat/templates/chat/pre_sleep_q.html
  src/chat/templates/chat/sleep_q.html
  src/chat/urls.py
  src/chat/views.py
  src/collected_static/chat/css/sleep_q.css
  src/collected_static/chat/js/sleep_q.js
  src/groups/templates/groups/home.html
  src/groups/views.py
Labels: enhancement
