Repository s1f10220227/sleep-comm-ai, pull requests merged in 2025-01, with the labels that each got.

#130 Add app name and tagline to the navbar
  src/templates/base.html
Labels: enhancement

#133 Add feature to display group mission and today's user response on the home screen
  src/groups/templates/groups/home.html
  src/groups/views.py
Labels: enhancement

#135 Feature/ready check and lock mission
  src/chat/migrations/0008_missiongenerate_missiongeneratevote.py
  src/chat/migrations/0009_remove_missiongeneratevote_mission_option.py
  src/chat/migrations/0010_merge_20250104_2259.py
  src/chat/models.py
  src/chat/templates/chat/room.html
  src/chat/urls.py
  src/chat/views.py
  src/groups/migrations/0005_group_is_join_closed.py
  src/groups/models.py
  src/groups/views.py
Labels: enhancement

#137 Feature/revoke votes when member leaves
  src/groups/views.py
Labels: bug

#140 remove profile
  src/accounts/templates/accounts/profile.html
  src/accounts/urls.py
  src/accounts/views.py
  src/templates/base.html
Labels: enhancement

#141 Feature/add ai lead logic
  src/chat/consumers.py
  src/chat/tasks.py
  src/chat/templates/chat/room.html
  src/chat/templates/chat/sleep_q.html
  src/chat/views.py
  src/config/celery.py
  src/groups/migrations/0005_group_init_message_sent.py
  src/groups/models.py
Labels: enhancement

#147 Feature/admin model export
  django/requirements.txt
  src/chat/admin.py
  src/config/settings.py
  src/groups/admin.py
Labels: enhancement

#148 Adjustment of prompts to generate mission proposals
  src/chat/views.py
Labels: enhancement, help wanted, question

#150 Feature/improve overall UI
  src/accounts/models.py
  src/accounts/static/accounts/css/login_signup.css
  src/accounts/templates/accounts/login.html
  src/accounts/templates/accounts/login_signup.html
  src/accounts/templates/accounts/privacy_policy.html
  src/accounts/templates/accounts/signup.html
  src/accounts/views.py
  src/chat/consumers.py
  src/chat/static/chat/css/room.css
  src/chat/static/chat/css/sleep_q.css
  src/chat/static/chat/js/room.js
  src/chat/static/chat/js/sleep_q.js
  src/chat/tasks.py
  src/chat/templates/chat/pre_sleep_q.html
  src/chat/templates/chat/room.html
  src/chat/templates/chat/sleep_q.html
  src/chat/templatetags/markdown_extras.py
  src/chat/views.py
  src/collected_static/accounts/css/login_signup.css
  src/collected_static/chat/css/room.css
  src/collected_static/chat/css/sleep_q.css
  src/collected_static/chat/js/room.js
  src/collected_static/chat/js/sleep_q.js
  src/collected_static/groups/css/home.css
  src/collected_static/groups/js/home.js
  src/collected_static/progress/css/sleep_data.css
  src/collected_static/progress/js/sleep_data.js
  src/groups/static/groups/css/home.css
  src/groups/static/groups/js/home.js
  src/groups/templates/groups/home.html
  src/groups/views.py
  src/progress/static/progress/css/sleep_data.css
  src/progress/static/progress/js/sleep_data.js
  src/progress/templates/progress/progress_check.html
  src/progress/templates/progress/sleep_data.html
  src/progress/urls.py
  src/progress/views.py
  src/templates/base.html
Labels: enhancement
